### ISSUE TITLE
Contact Operations – Registry – RegisterInstallation

### ISSUE THREAD

**Issue by jac18281828** [xmtp/xps-gateway#22]
### Discussed in https://github.com/xmtp/xps-gateway/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **jac18281828** December 22, 2023</sup>
Initial discussion is [here](https://github.com/xmtp/libxmtp/discussions/274)

Device installation is supported by `RegisterInstallation`.

#### Request:

- **Method:** `POST`
- **URL:** `/rpc/v1/registerInstallation`
- **Headers:**
  - `Content-Type: application/json`
- **Body:**
  - **JSON Object:** 
    - `jsonrpc`: `"2.0"`
    - `method`: `"registerInstallation"`
    - `params`: Array (optional parameters as required)
    - `id`: Request identifier (integer or string)

#### Description
The `registerInstallation` endpoint is responsible for storing the contact bundle for the XMTP device installation.   The request must be made to a valid did with an XMTP profile.

#### Request
The request for this endpoint should contain the necessary information to authenticate and validate the installation request including the wallet signed payload

##### Parameters:
- `DID` (string): Unique XMTP identifier for the user requesting the installation.
- `name` (bytes32): Unique identifier naming bundled contents.  **NOTE** 32 byte maximum
- `value` (bytes): Installation bundle bytes payload.
- `V` (int): signature V
- `R` (bytes): signature R
- `S` (bytes): signature S

##### Example Request:
```json
{
  "jsonrpc": "2.0",
  "method": "registerInstallation",
  "params": {
    "did": "12345",
    "name": "xmtp/contact_installation",
    "value": "#######",
    "signature": {
      "V": "12345",
      "R": "valueR",
      "S": "valueS"
    }
  },
  "id": 1
}
```

#### Response
The response will indicate whether the installation is granted and may include additional information or instructions.

##### Result Fields:
- `status` (string): The status of the request, e.g., 'completed'.
- `message` (string, optional): Additional information or reason for the decision.
- `tx` (string, optional): transaction receipt

##### Example Response:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "status": "completed",
    "message": "Installation request complete.",
    "tx": "<receipt>"
  },
  "id": 1
}
```

#### Error Handling
In case of an error, the response will include an error object with details.

##### Error Object Fields:
- `code` (integer): Numeric code representing the error type.
- `message` (string): Description of the error.

##### Example Error Response:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 403,
    "message": "User not authorized for installation."
  },
  "id": 1
}
```

#### Security Considerations
All requests to `registerInstallation` must be made over a secure channel. Ensure that user and application IDs are validated, and proper authentication mechanisms are in place to prevent unauthorized requests.
</div>

**Comment by insipx** [comment]
supported in #50
