### ISSUE TITLE
JSON RPC Endpoint: balance

### ISSUE THREAD

**Issue by jac18281828** [xmtp/xps-gateway#23]
### Discussed in https://github.com/xmtp/xps-gateway/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **jac18281828** December 19, 2023</sup>
To support monitoring of the gateway wallet balance it will be important to support simple transparency for the available funds on the gateway wallet.   This request is to implement a JSON RPC method `balance` which will return the current wallet balance.

### Documentation for JSON RPC Endpoint: `balance`

---

#### Description:
The `balance` endpoint retrieves the current balance of the internal wallet managed by the server. This endpoint is essential for applications that need to display or monitor the wallet's balance, especially in the context of cryptocurrency transactions or account management.

#### Request:

- **Method:** `POST`
- **URL:** `/rpc/v1/balance`
- **Headers:**
  - `Content-Type: application/json`
- **Body:**
  - **JSON Object:** 
    - `jsonrpc`: `"2.0"`
    - `method`: `"balance"`
    - `params`: Array (optional parameters as required)
    - `id`: Request identifier (integer or string)

**Example Request Body:**

```json
{
  "jsonrpc": "2.0",
  "method": "balance",
  "params": [],
  "id": 1
}
```

#### Response:

- **Success Status Code:** `200 OK`
- **Error Status Codes:**
  - `400 Bad Request` - Invalid request format or parameters.
  - `500 Internal Server Error` - Server or wallet-related error.

**Success Response Body:**

```json
{
  "jsonrpc": "2.0",
  "result": {
    "balance": "100.0 ETH",
    "unit": "ETH"
  },
  "id": 1
}
```

**Error Response Body:**

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Invalid parameters"
  },
  "id": 1
}
```

#### Error Handling:

- **Invalid Parameters:** Check if the request body is properly formatted and includes valid parameters.
- **Wallet or Server Errors:** Ensure that the server and wallet are operational. Consult server logs for detailed error information.

#### Security Considerations:

- **Authentication and Authorization:** Implement robust authentication and authorization checks to ensure only authorized users can access wallet balance information.
- **Secure Communication:** Utilize HTTPS to encrypt data in transit and prevent eavesdropping.

#### Usage Example:

```javascript
const requestBody = {
  jsonrpc: "2.0",
  method: "balance",
  params: [],
  id: 1
};

fetch('https://server.example.com/rpc/v1/balance', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(requestBody)
})
.then(response => response.json())
.then(data => console.log('Wallet Balance:', data.result))
.catch(error => console.error('Error:', error));
```
</div>

**Comment by triggeredcode** [comment]
Hey @jac18281828  I'm interested in the XPS Gateway project and would like to contribute. Could you consider me for the task assignment?

#### Quick Questions (Please tick as appropriate):
- **🛠 Skill Level:**
  - [ ] Suitable for beginners
  - [ ] Requires intermediate knowledge
  - [ ] Needs advanced expertise

- **⏰ Time Commitment:**
  - [ ] 3-7 hr
  - [ ] 8-12 hr
  - [ ] 13+ hrs

**Comment by jac18281828** [comment]
> Hey @jac18281828 I'm interested in the XPS Gateway project and would like to contribute. Could you consider me for the task assignment?
> 
> #### Quick Questions(Please tick as appropriate):
> * **🛠 Skill Level Needed:**
>   
>   * [x]  Suitable for beginners
>   * [ ]  Requires intermediate knowledge
>   * [ ]  Needs advanced expertise
> * **⏰ Time Commitment:**
>   
>   * [ ]  3-7 hr
>   * [x]  8-12 hr
>   * [ ]  13+ hrs

Yes, of course your contribution would be very welcome.   I suggest considering #28 a prerequisite to this one or #19 as a standalone issue.   Feel free to connect with us on our Discord as well as I'd be happy to talk you through any of the steps to get going.    Perhaps, once you feel comfortable enough to get started we could arrange an intro call as well to kick things off in the right direction.   Let me know what works best for you!
